#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2020 OpenWrt.org
# Copyright (C) 2022 ImmortalWrt.org

START=99
USE_PROCD=1

start_instance() {
    local cfg="$1"
    local type
    config_get type "$cfg" TYPE

    case "$type" in
        mesh)  # 修改 happynet 为 mesh
            local enabled
            config_get_bool enabled "$cfg" 'enabled' '0'
            [ "$enabled" = "1" ] || return 1

            local masquerade compress select_rtt tunname mode ipaddr prefix mtu
            local supernode port second_supernode second_port
            local community key route

            config_get_bool masquerade "$cfg" 'masquerade' '0'
            config_get_bool compress "$cfg" 'compress' '1'
            config_get_bool select_rtt "$cfg" 'select_rtt' '1'
            config_get tunname "$cfg" 'tunname'
            config_get mode "$cfg" 'mode'
            config_get ipaddr "$cfg" 'ipaddr'
            config_get prefix "$cfg" 'prefix'
            config_get mtu "$cfg" 'mtu'
            config_get supernode "$cfg" 'supernode'
            config_get port "$cfg" 'port'
            config_get second_supernode "$cfg" 'second_supernode'
            config_get second_port "$cfg" 'second_port'
            config_get community "$cfg" 'community'
            config_get key "$cfg" 'key'
            config_get_bool route "$cfg" 'route' '0'

            local address
            address="$ipaddr/$prefix"
            [ "$mode" != 'dhcp' ] || address='0.0.0.0'

            procd_open_instance "mesh_$cfg"
            procd_set_param command /usr/bin/mesh -f
            procd_append_param command -u 0 -g 0
            procd_append_param command -d "$tunname"
            procd_append_param command -a "$mode:$address"
            procd_append_param command -c "$community"
            procd_append_param command -l "$supernode:$port"
            [ -z "$key" ] || procd_append_param command -k "$key"
            [ -z "$mtu" ] || procd_append_param command -M "$mtu"
            [ -z "$second_supernode" -o -z "$second_port" ] || procd_append_param command -l "$second_supernode:$second_port"
            [ "$route" = "0" ] || procd_append_param command -r
            [ "$compress" = "0" ] || procd_append_param command -z1
            [ "$select_rtt" = "0" ] || procd_append_param command --select-rtt

            procd_set_param limits core="unlimited"
            procd_set_param limits nofile="1000000 1000000"
            procd_set_param stdout 1
            procd_set_param stderr 1
            procd_set_param respawn
            procd_close_instance
            ;;
    esac
}

stop_instance() {
    local cfg="$1"
    procd_close_instance "mesh_$cfg"
}

start_service() {
    config_load 'mesh'
    config_foreach start_instance 'mesh'
}

stop_service() {
    config_load 'mesh'
    config_foreach stop_instance 'mesh'
}

reload_service() {
    stop_service
    start_service
}

service_triggers() {
    procd_add_reload_trigger "mesh"
}
